### PR TITLE
twitter harvester for search and filter.

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

**Comment by justinlittman** [comment]
For now, I would base the evaluation on code review, unit tests, and integration tests.  Once this is merged into master, it will be easier to do more testing.

**Comment by rajatvij** [comment]
Please provide steps for testing.

**Comment by justinlittman** [comment]
Steps to test:
```
git clone https://github.com/gwu-libraries/sfm-twitter-harvester.git
cd sfm-twitter-harvester
git branch --track sfm_t46-twitter origin/sfm_t46-twitter
git checkout sfm_t46-twitter
cd docker
cp dev.docker-compose.yml docker-compose.yml
docker-compose build
docker-compose up -d
```

Log into RabbitMQ management console (http://localhost:15672) and check for twitter harvester queues.  (There should be 3 - 2 for twitter harvester and 1 for twitter rest harvester.)

Create a test queue and bind to `harvest.status.*.*`, `harvest.start.web`, and `warc_created`.

Publish a message to `sfm_exchange` with routing key `harvest.start.twitter.twitter_search` requesting a search on GWU and Gelman:
```
{
    "id": "test:1",
    "type": "twitter_search",
    "seeds": [
        {
            "token": "gwu"
        },
        {
            "token": "gelman"
        }
    ],
    "credentials": {
        "consumer_key": "EHdoTe7ksBgflP5nUalEfhaeo",
        "consumer_secret": "ZtUpemtBkf2cEmaqiy52Ddihu9FPAiLebuMOmqN0jeQtXeAlen",
        "access_token": "481186914-c2yZjbk1np0Z5MWEFYYQKSQNFBXd8T9r4k90YkJl",
        "access_token_secret": "jK9QOmn5Vmfgl2AN6KgfmCKRqV8ThXVQ1G6qQg8BCejvp"
    },
    "collection": {
        "id": "test_collection",
        "path": "/tmp/test_collection"
    }
}
```

Wait and then check the test queue for messages.  You should expect a web harvest start message, a warc created, and a harvest status message in which the status is completed success.  Before doing more testing, make sure to purge the test queue.

Shell into one of the harvester containers and look for the WARC in `/tmp/test_collection` (there should only be one):
```
docker exec -it docker_sfmtwitterrestharvester_1 /bin/bash
cd /tmp/test_collection
ls
```

To test filter stream harvester, publish a harvest start message to `sfm_exchange` with the routing key `harvest.start.twitter.twitter_filter`:
```
{
    "id": "test:2",
    "type": "twitter_filter",
    "seeds": [
        {
            "token": "obama"
        }
    ],
    "credentials": {
        "consumer_key": "EHdoTe7ksBgflP5nUalEfhaeo",
        "consumer_secret": "ZtUpemtBkf2cEmaqiy52Ddihu9FPAiLebuMOmqN0jeQtXeAlen",
        "access_token": "481186914-c2yZjbk1np0Z5MWEFYYQKSQNFBXd8T9r4k90YkJl",
        "access_token_secret": "jK9QOmn5Vmfgl2AN6KgfmCKRqV8ThXVQ1G6qQg8BCejvp"
    },
    "collection": {
        "id": "test_collection",
        "path": "/tmp/test_collection"
    }
}
```

Wait a **few hours** and then send a harvest stop message to `sfm_exchange` with routing key `harvest.stop.twitter.twitter_filter`:
```
{
    "id": "test:2"
}
```

This time when you check the test queue for messages, you should expect to find multiple warc created, harvest status, and web harvest start messages.  The status of the harvest status message should be running, except for the last which should be completed success.

Again, shell into one of the harvester containers and look for new WARCs in `/tmp/test_collection` (there should be more than one).

**Comment by justinlittman** [comment]
When publishing the messages above, add a property called "content_type" with value "application/json".

**Comment by justinlittman** [comment]
@rajatvij : This is re--ready for testing.

**Pull request merged**
