### PR TITLE
T1103 exporter v2

### PR DESCRIPTION
**Pull request by dolsysmith**
#### Summary

Updates harvester and exporter for Twitter v. 2 search and timeline types. Test in conjunction with `twitter-v2` branch in `sfm-ui` and `t1103-twitter-v2-search` branch in `sfm-utils`. (Note that this PR includes code both for the v2. harvester and the v2. exporter.)

#### To prepare

1. Update `docker-compose.yml` to use the v2 Twitter rest exporter as well as the existing exporter. See `example.docker-compose.yml` in the `t1103-twitter2-exporter` branch of `sfm-docker`. 
2. Change the compose file to build the local image for **both** the `twitterrestexporter` and the `twitterrestexporter2` services. 
3. Make sure both services are using code from the locally mapped volumes.

#### To test

1. Create collections for the Twitter 2 search and Twitter 2 user timeline harvest types.
2. Make sure collections harvest without errors.
3. Create exports of all types from these collections.
4. Create exports of all types from Twitter v1 search and Twitter v1 user timeline collections.

### CODE REVIEW

**Comment by dolsysmith** [comment]
Updated to fix errors when running an incremental search with a `start_time` or `end_time` parameter. The parameter(s) will be observed on the first run but ignored on subsequent runs (when the `since_id` param is present).

**Comment by dolsysmith** [comment]
Added support for `MAX_DATAFRAME_ROWS` as an environment variable. (See changes to the example `.env` and `docker-compose` files in the corresponding branch on the sfm-docker repo.) If the variable is present, the exporter will use that, making it easier to tweak for performance. (If not, it will use a default value.)

**Comment by dolsysmith** [comment]
Update: the following types of searches should now _not_ produce errors:
1. Incremental searches where the last search > 7 days ago. (SFM will silently ignore the `since_id` parameter in these cases.)
2. Searches where the `start_time` parameter is > 7 days ago. (SFM will silently ignore the parameter.)

**Comment by kerchner** [comment]
Recommended testing:
- Try different collection types
- Try turning back on collection stopped > 7 days ago

Record testing results here in PR

**Comment by kerchner** [comment]
I tested the following and they worked as expected, both in terms of performing harvests, and generating exports.

- v2 User Timeline and export 
- v2 Search 

Although the collection type for v2 search (on the dropdown list) does say "**Recent** tweets matching a query from the standard version 2 API" the seed form does include parameters for `Start time` and `End time`.  Using these without an Academic Researcher credential returns a 400 error from the harvest.

Are we planning to have a single v2 search type that can be used with or without academic researcher rights on the token?  - If so, then the description on the collection types dropdown list will need to be generalized, but we should add notes on the form warning that use of Start time / End time requires academic researcher access (or will result in an error).
- If we're planning to have two types, then we should duplicate this collection type, and remove the Start time/End time parameters from the non-academic researcher search collection type.

I am also finding that running a `dehydrate` export (identifiers only) never seems to finish, but I first need to confirm that there are no issues with my local setup (location of data directories, docker-compose file, etc.).  Will follow up on that in a separate comment.

**Comment by kerchner** [comment]
@dolsysmith indicated that UI has been updated.  I plan to retest with the latest code.

**Comment by kerchner** [comment]
@dolsysmith The issue with dehydrate export is confirmed as fixed.  No further issues found with v2 exports.

The issue referenced above, whereby the v2 non-academic search seed UI is displaying start/end time fields, remains, but I see that it was never noted in https://github.com/gwu-libraries/sfm-ui/ so I have created https://github.com/gwu-libraries/sfm-ui/issues/1129 .

**Pull request merged**
