### PR TITLE
refs #61. Plugs in twarc support for user timeline and sample stream.

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

**Comment by justinlittman** [comment]
Here's a docker-compose.yml file that can be run from the context of sfm-ui to bring up an environment for testing:
```
sfmdb:
    image: gwul/sfm-ui-db:master
#    build: db
    environment:
        - POSTGRES_PASSWORD=gherD42#dl5
        - TZ=EST
sfmapp:
#    image: gwul/sfm-ui:dev
#    build: app-dev
#    build: app-dev-runserver
    image: gwul/sfm-ui:dev-runserver
#    build: app-prod
    ports:
        - "8081:80"
    links:
        - sfmdb:db
        - sfmrabbit:mq
    environment:
        - SFM_DEBUG=True
        - SFM_APSCHEDULER_LOG=DEBUG
#        - SFM_DJANGO_LOG=DEBUG
        - SFM_UI_LOG=DEBUG
        - SFM_FIVE_MINUTE_SCHEDULE=True
        - TZ=EST
    volumes:
        - ~/Data/sfm3/sfm-ui:/opt/sfm-ui
    volumes_from:
        - sfmdata:ro
sfmrabbit:
    image: rabbitmq@sha256:397382d2b222f3a298a6c74e93f348fb16f9a7fde2c02ba14122624d852daae3
    #RabbatMQ 3-management
    ports:
        - "15672:15672"
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER=sfm_user
        - RABBITMQ_DEFAULT_PASS=password
        - TZ=EST
sfmdata:
    image: ubuntu:14.04
    command: /bin/true
    volumes:
#        - ~/tmp/sfmtest:/sfm-data
         - /sfm-data
         - TZ=EST
#sfmtwitterrestharvester:
#    image: gwul/sfm-twitter-rest-harvester:master
#    links:
#        - sfmrabbit:mq
#    restart: always
#    environment:
#        - DEBUG=True
#        - TZ=EST
#    volumes_from:
#        - sfmdata
sfmtwitterrestharvester:
    image: gwul/sfm-twitter-rest-harvester:dev
    links:
        - sfmrabbit:mq
    volumes:
        - "../../sfm-twitter-harvester:/opt/sfm-twitter-harvester"
        - "../../sfm-utils:/opt/sfm-utils"
        - "../../warcprox:/opt/warcprox"
    environment:
        - TZ=EST
        - DEBUG=True
    volumes_from:
        - sfmdata
```

Note that since streams are not yet supported from the UI, only the user timeline can be tested.

**Comment by kerchner** [comment]
@justinlittman Has the docker-compose you use changed since the example you posted?  With the docker-compose as-is, I get:
```Service "sfmapp" mounts volumes from "sfmdata:ro", which is not the name of a service or container.```

**Comment by kerchner** [comment]
@justinlittman disregard previous comment; I was able to extend my own docker-compose to create a working set of containers to include a twitter rest harvester.

**Comment by kerchner** [comment]
:+1:

**Pull request merged**
