### PR TITLE
Improved organization/ordering of export columns. Done together with …

### PR DESCRIPTION
**Pull request by kerchner**
…https://github.com/gwu-libraries/sfm-ui/issues/552

### CODE REVIEW

**Comment by kerchner** [comment]
@adityadharne The test here is to verify that the export still works. Once you merge it, notify @yonahbg so that he can review https://github.com/gwu-libraries/sfm-ui/pull/581 and validate that the data dictionary documentation matches the newly updated twitter export.

**Comment by adityadharne** [comment]
@kerchner Travis is failing here

**Comment by kerchner** [comment]
Thank you @adityadharne , it looks like I need to update the tests!

**Comment by adityadharne** [comment]
The export works, will merge once Travis passes.

**Comment by kerchner** [comment]
@adityadharne : The unit tests run locally; not sure why the CI build is getting hung up on the error shown in the Travis build details.  @justinlittman advises proceeding with the build and observing the Travis build of master after the merge.

**Comment by adityadharne** [comment]
Observe Travis for master after merging.

**Pull request merged**
